project_name: rails
project_root: .
windows:
    - server-test:
        layout: even-horizontal
        panes:
            - rails server
            - bundle exec guard
    - editor:
        panes:
            - vim
    - sandbox:
            - rails console --sandbox
    - shell: #empty
