---

- name: Create cron backup development
  cron:
    name: Sync dev folder to data drive
    hour: "*/3"
    minute: 0
    job: "rsync -avh --delete /home/eduardo/dev /media/data/eduardo"

- name: Create cron backup of data drive
  cron:
    name: Backup everything in data drive to data backup drive
    hour: 16
    minute: 0
    job: "rsync -avh --exclude=lost+found --delete /media/data /media/data-bkp"

- name: Create cron backup to nas
  cron:
    name: Backup to nas
    hour: 12
    minute: 0
    weekday: 5
    job: "/home/eduardo/bin/backup_nas"
